import type { Metadata } from "next";
import "./globals.css";
import { Layout } from "@/components/craft";
import { Roboto, Rosario } from "next/font/google";
import { Footer } from "@/components/footer";
import { Navbar } from "@/components/navbar";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
  variable: "--font-roboto",
});
const rosario = Rosario({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-rosario",
});

export const metadata: Metadata = {
  title: "Budokenkyudo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Layout>
      <body
        // className={`${roboto.variable} ${rosario.variable} bg-background font-sans text-foreground antialiased`}
        className={`${roboto.variable} ${rosario.variable} bg-gradient-to-b from-background to-white font-sans text-foreground antialiased`}
      >
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </Layout>
  );
}
