import type { Metadata } from "next";
import "./globals.css";
import { Layout, Main } from "@/components/craft";
import { Roboto } from "next/font/google";
import { Footer } from "@/components/footer";
import { Navbar } from "@/components/navbar";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Budokenkyudo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Layout>
      <body className={`${roboto.variable} antialiased`}>
        <Navbar />
        <Main>{children}</Main>
        <Footer />
      </body>
    </Layout>
  );
}
